apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incident-bot

bases:
  - ../../base/

images:
  - name: eb129/incident-bot
    newTag: v1.4.8

configMapGenerator:
  - name: incident-bot-config
    files:
      - config.yaml

secretGenerator:
  - name: incident-bot
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
