apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: incident-bot

resources:
  - namespace.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - service.yaml
  - db.yaml
