version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['./wait-for-it.sh', 'db:5432', '--', 'python3', 'main.py']
    depends_on:
      - db
    environment:
      SLACK_APP_TOKEN: 'xapp-1-...'
      SLACK_BOT_TOKEN: 'xoxb-...'
      SLACK_USER_TOKEN: 'xoxp-...'
      POSTGRES_HOST: db
      POSTGRES_DB: incident_bot
      POSTGRES_USER: incident_bot
      POSTGRES_PASSWORD: somepassword
      POSTGRES_PORT: 5432
      PAGERDUTY_API_TOKEN: ''
      PAGERDUTY_API_USERNAME: ''
      STATUSPAGE_API_KEY: ''
      STATUSPAGE_PAGE_ID: ''
      STATUSPAGE_URL: ''
      CONFLUENCE_API_URL: 'https://my-company.atlassian.net'
      CONFLUENCE_API_USERNAME: ''
      CONFLUENCE_API_TOKEN: ''
      DEFAULT_WEB_ADMIN_PASSWORD: 'foobar1234'
      JWT_SECRET_KEY: 'supersecret'
      CONFIG_FILE_PATH: '/config/incident-bot/config.yaml'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    links:
      - db
    volumes:
      # Wherever the config file lives, root by default
      - ./backend/config.yaml:/config/incident-bot/config.yaml
  db:
    image: postgres:13
    command:
      ['postgres', '-c', 'log_statement=all', '-c', 'log_destination=stderr']
    hostname: db
    environment:
      POSTGRES_PASSWORD: 'somepassword'
      POSTGRES_USER: 'incident_bot'
    ports:
      - 5432:5432
