version: 2
jobs:
  build-bot:
    environment:
      IMAGE_NAME: eb129/incident-bot
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish amd64 Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --tag $IMAGE_NAME:$IMAGE_TAG .
  build-bot-arm64:
    environment:
      IMAGE_NAME: eb129/incident-bot
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish arm64 Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --file Dockerfile.arm64 --tag $IMAGE_NAME:$IMAGE_TAG-arm64 .
  publish-bot:
    environment:
      IMAGE_NAME: eb129/incident-bot
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish amd64 Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --tag $IMAGE_NAME:$IMAGE_TAG .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
  publish-bot-arm64:
    environment:
      IMAGE_NAME: eb129/incident-bot
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish arm64 Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --file Dockerfile.arm64 --tag $IMAGE_NAME:$IMAGE_TAG-arm64 .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG-arm64
  publish-docs:
    environment:
      IMAGE_NAME: eb129/incident-bot-docs
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo 'export IMAGE_TAG=$(cat version)' >> "$BASH_ENV"
            source "$BASH_ENV"
            docker build --tag $IMAGE_NAME:$IMAGE_TAG --file ./docs/Dockerfile .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  main:
    jobs:
      - build-bot:
          filters:
            branches:
              ignore: main
      - build-bot-arm64:
          filters:
            branches:
              ignore: main
      - publish-bot:
          filters:
            branches:
              only: main
      - publish-bot-arm64:
          filters:
            branches:
              only: main
      - publish-docs:
          filters:
            branches:
              only: main
