apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: incident-bot
  name: incident-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: incident-bot
    spec:
      containers:
        - name: incident-bot
          image: eb129/incident-bot
          command: ['./wait-for-it.sh']
          args: ['db:5432', '--', 'python3', 'main.py']
          envFrom:
            - secretRef:
                name: incident-bot
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 512M
            requests:
              cpu: 250m
              memory: 256M
          volumeMounts:
            - name: incident-bot-config
              mountPath: /config/incident-bot
            - mountPath: /config/google-creds.json
              name: google-creds
              readOnly: true
              subPath: google-creds.json
      volumes:
        - name: incident-bot-config
          configMap:
            name: incident-bot-config
        - name: google-creds
          secret:
            defaultMode: 420
            secretName: google-creds
